### ISSUE TITLE
Front End Repo Config

### ISSUE THREAD

**Issue by 4cody** [BigOleEnterprise/Tat-Tac-Documentation#2]
Front end repo is currently set as private

Suggest changing to public or changing all repos to private

**Comment by cchave17** [comment]
Good call
I think setting everything to public would be best, we just have to make sure we dont commit any creds hard coded in. all creds should just be environment variables. I forget the command to delete everything from previous commit if you forget, but I know there is a command for that. its much harder to delete a commit if its further back in history.

**Comment by cchave17** [comment]
done
